<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDgBsNY1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDgBsNY1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDgBsNY1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDgBsNY1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDgBsNY1\App_KernelDevDebugContainer([
    'container.build_hash' => 'DgBsNY1',
    'container.build_id' => '37878df2',
    'container.build_time' => 1619516781,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDgBsNY1');
